// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4fa-AmXpjDoQzt3-kktgVi3NUfNTqEI',
    appId: '1:541719658191:web:abb5a63df033a5f27641ba',
    messagingSenderId: '541719658191',
    projectId: 'study-tracker-d18b1',
    authDomain: 'study-tracker-d18b1.firebaseapp.com',
    storageBucket: 'study-tracker-d18b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQwy-2e16UI2IzCSOC4Pw6VwEzKz7P5JQ',
    appId: '1:541719658191:android:5ea3be7189c78bb37641ba',
    messagingSenderId: '541719658191',
    projectId: 'study-tracker-d18b1',
    storageBucket: 'study-tracker-d18b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSHZtthbrTMEYA6P2RkfE6LpE2l0C-cA',
    appId: '1:541719658191:ios:885467d5dab97e467641ba',
    messagingSenderId: '541719658191',
    projectId: 'study-tracker-d18b1',
    storageBucket: 'study-tracker-d18b1.firebasestorage.app',
    iosBundleId: 'com.example.studyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSHZtthbrTMEYA6P2RkfE6LpE2l0C-cA',
    appId: '1:541719658191:ios:885467d5dab97e467641ba',
    messagingSenderId: '541719658191',
    projectId: 'study-tracker-d18b1',
    storageBucket: 'study-tracker-d18b1.firebasestorage.app',
    iosBundleId: 'com.example.studyTrackerApp',
  );
}
